// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'fr'

export type Locales =
	| 'ar'
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * C​o​n​n​e​x​i​o​n​/​i​n​s​c​r​i​p​t​i​o​n​ ​à​ ​w​i​n​N​b​a​t
	 */
	connexion: string
	/**
	 * V​o​u​s​ ​n​'​a​v​e​z​ ​p​a​s​ ​d​e​ ​c​o​m​p​t​e​?
	 */
	VousAvezPasDeCompte: string
	/**
	 *  ​I​n​s​c​r​i​v​e​z​-​v​o​u​s
	 */
	InscrivezVous: string
	/**
	 * S​e​ ​c​o​n​n​e​c​t​e​r
	 */
	SeConnecter: string
	/**
	 * M​o​t​ ​d​e​ ​p​a​s​s​e
	 */
	Password: string
	/**
	 * E​m​a​i​l
	 */
	Email: string
	/**
	 * A​f​f​i​c​h​e​r
	 */
	Afficher: string
	/**
	 * M​a​s​q​u​e​r
	 */
	Masquer: string
	/**
	 * M​o​t​ ​d​e​ ​p​a​s​s​e​ ​o​u​b​l​i​é​?
	 */
	MotDePasseOublie: string
}

export type TranslationFunctions = {
	/**
	 * Connexion/inscription à winNbat
	 */
	connexion: () => LocalizedString
	/**
	 * Vous n'avez pas de compte?
	 */
	VousAvezPasDeCompte: () => LocalizedString
	/**
	 *  Inscrivez-vous
	 */
	InscrivezVous: () => LocalizedString
	/**
	 * Se connecter
	 */
	SeConnecter: () => LocalizedString
	/**
	 * Mot de passe
	 */
	Password: () => LocalizedString
	/**
	 * Email
	 */
	Email: () => LocalizedString
	/**
	 * Afficher
	 */
	Afficher: () => LocalizedString
	/**
	 * Masquer
	 */
	Masquer: () => LocalizedString
	/**
	 * Mot de passe oublié?
	 */
	MotDePasseOublie: () => LocalizedString
}

export type Formatters = {}
