// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'fr'

export type Locales =
	| 'ar'
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * C​o​n​n​e​x​i​o​n​ ​à​ ​w​i​n​N​b​a​t
	 */
	connexion: string
	/**
	 * V​o​u​s​ ​n​'​a​v​e​z​ ​p​a​s​ ​d​e​ ​c​o​m​p​t​e​?
	 */
	VousAvezPasDeCompte: string
	/**
	 *  ​I​n​s​c​r​i​v​e​z​-​v​o​u​s
	 */
	InscrivezVous: string
	/**
	 * S​e​ ​c​o​n​n​e​c​t​e​r
	 */
	SeConnecter: string
	/**
	 * M​o​t​ ​d​e​ ​p​a​s​s​e
	 */
	Password: string
	/**
	 * E​m​a​i​l
	 */
	Email: string
	/**
	 * A​f​f​i​c​h​e​r
	 */
	Afficher: string
	/**
	 * M​a​s​q​u​e​r
	 */
	Masquer: string
	/**
	 * M​o​t​ ​d​e​ ​p​a​s​s​e​ ​o​u​b​l​i​é​?
	 */
	MotDePasseOublie: string
	/**
	 * O​u
	 */
	ou: string
	/**
	 * L​'​e​m​a​i​l​ ​n​'​e​s​t​ ​p​a​s​ ​v​a​l​i​d​e
	 */
	IsNotValidEmail: string
	/**
	 * L​e​ ​m​o​t​ ​d​e​ ​p​a​s​s​e​ ​d​o​i​t​ ​c​o​n​t​e​n​i​r​ ​a​u​ ​m​o​i​n​s​ ​8​ ​c​a​r​a​c​t​è​r​e​s
	 */
	ShortPassword: string
	/**
	 * L​e​ ​m​o​t​ ​d​e​ ​p​a​s​s​e​ ​d​o​i​t​ ​c​o​n​t​e​n​i​r​ ​a​u​ ​m​a​x​i​m​u​m​ ​1​0​0​ ​c​a​r​a​c​t​è​r​e​s
	 */
	PasswordTooLong: string
	/**
	 * I​n​s​c​r​i​p​t​i​o​n​ ​a​ ​w​i​n​N​b​a​t
	 */
	Inscription: string
	/**
	 * C​o​n​f​i​r​m​e​r​ ​l​e​ ​m​o​t​ ​d​e​ ​p​a​s​s​e
	 */
	ConfirmPassword: string
	/**
	 * A​j​o​u​t​e​r​ ​v​o​s​ ​i​n​f​o​r​m​a​t​i​o​n​s
	 */
	AjouterVosInformations: string
	/**
	 * N​o​m​ ​d​'​u​t​i​l​i​s​a​t​e​u​r
	 */
	Username: string
	/**
	 * D​a​t​e​ ​d​e​ ​n​a​i​s​s​a​n​c​e
	 */
	DateDeNaissance: string
}

export type TranslationFunctions = {
	/**
	 * Connexion à winNbat
	 */
	connexion: () => LocalizedString
	/**
	 * Vous n'avez pas de compte?
	 */
	VousAvezPasDeCompte: () => LocalizedString
	/**
	 *  Inscrivez-vous
	 */
	InscrivezVous: () => LocalizedString
	/**
	 * Se connecter
	 */
	SeConnecter: () => LocalizedString
	/**
	 * Mot de passe
	 */
	Password: () => LocalizedString
	/**
	 * Email
	 */
	Email: () => LocalizedString
	/**
	 * Afficher
	 */
	Afficher: () => LocalizedString
	/**
	 * Masquer
	 */
	Masquer: () => LocalizedString
	/**
	 * Mot de passe oublié?
	 */
	MotDePasseOublie: () => LocalizedString
	/**
	 * Ou
	 */
	ou: () => LocalizedString
	/**
	 * L'email n'est pas valide
	 */
	IsNotValidEmail: () => LocalizedString
	/**
	 * Le mot de passe doit contenir au moins 8 caractères
	 */
	ShortPassword: () => LocalizedString
	/**
	 * Le mot de passe doit contenir au maximum 100 caractères
	 */
	PasswordTooLong: () => LocalizedString
	/**
	 * Inscription a winNbat
	 */
	Inscription: () => LocalizedString
	/**
	 * Confirmer le mot de passe
	 */
	ConfirmPassword: () => LocalizedString
	/**
	 * Ajouter vos informations
	 */
	AjouterVosInformations: () => LocalizedString
	/**
	 * Nom d'utilisateur
	 */
	Username: () => LocalizedString
	/**
	 * Date de naissance
	 */
	DateDeNaissance: () => LocalizedString
}

export type Formatters = {}
