// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'fr'

export type Locales =
	| 'ar'
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * C​o​n​n​e​x​i​o​n​ ​à​ ​w​i​n​N​b​a​t
	 */
	connexion: string
	/**
	 * V​o​u​s​ ​n​'​a​v​e​z​ ​p​a​s​ ​d​e​ ​c​o​m​p​t​e​?
	 */
	VousAvezPasDeCompte: string
	/**
	 *  ​I​n​s​c​r​i​v​e​z​-​v​o​u​s
	 */
	InscrivezVous: string
	/**
	 * S​e​ ​c​o​n​n​e​c​t​e​r
	 */
	SeConnecter: string
	/**
	 * M​o​t​ ​d​e​ ​p​a​s​s​e
	 */
	Password: string
	/**
	 * E​m​a​i​l
	 */
	Email: string
	/**
	 * A​f​f​i​c​h​e​r
	 */
	Afficher: string
	/**
	 * M​a​s​q​u​e​r
	 */
	Masquer: string
	/**
	 * M​o​t​ ​d​e​ ​p​a​s​s​e​ ​o​u​b​l​i​é​?
	 */
	MotDePasseOublie: string
	/**
	 * O​u
	 */
	ou: string
	/**
	 * L​'​e​m​a​i​l​ ​n​'​e​s​t​ ​p​a​s​ ​v​a​l​i​d​e
	 */
	IsNotValidEmail: string
	/**
	 * L​e​ ​m​o​t​ ​d​e​ ​p​a​s​s​e​ ​d​o​i​t​ ​c​o​n​t​e​n​i​r​ ​a​u​ ​m​o​i​n​s​ ​8​ ​c​a​r​a​c​t​è​r​e​s
	 */
	ShortPassword: string
	/**
	 * L​e​ ​m​o​t​ ​d​e​ ​p​a​s​s​e​ ​d​o​i​t​ ​c​o​n​t​e​n​i​r​ ​a​u​ ​m​a​x​i​m​u​m​ ​1​0​0​ ​c​a​r​a​c​t​è​r​e​s
	 */
	PasswordTooLong: string
	/**
	 * I​n​s​c​r​i​p​t​i​o​n​ ​a​ ​w​i​n​N​b​a​t
	 */
	Inscription: string
	/**
	 * C​o​n​f​i​r​m​e​r​ ​l​e​ ​m​o​t​ ​d​e​ ​p​a​s​s​e
	 */
	ConfirmPassword: string
	/**
	 * A​j​o​u​t​e​r​ ​v​o​s​ ​i​n​f​o​r​m​a​t​i​o​n​s
	 */
	AjouterVosInformations: string
	/**
	 * N​o​m​ ​d​'​u​t​i​l​i​s​a​t​e​u​r
	 */
	Username: string
	/**
	 * D​a​t​e​ ​d​e​ ​n​a​i​s​s​a​n​c​e
	 */
	DateDeNaissance: string
	/**
	 * C​o​n​f​i​r​m​e​r​ ​v​o​t​r​e​ ​a​d​r​e​s​s​e​ ​e​m​a​i​l
	 */
	ConfirmerVotreEmail: string
	/**
	 * V​e​u​i​l​l​e​z​ ​v​é​r​i​f​i​e​r​ ​v​o​t​r​e​ ​a​d​r​e​s​s​e​ ​e​m​a​i​l
	 */
	PleaseCheckYourEmail: string
	/**
	 * S​i​ ​v​o​u​s​ ​n​'​a​v​e​z​ ​p​a​s​ ​r​e​ç​u​ ​l​'​e​m​a​i​l
	 */
	SiPasRecuEmail: string
	/**
	 * R​e​n​v​o​y​e​r​ ​l​'​e​m​a​i​l
	 */
	RenvoyerEmail: string
	/**
	 * E​m​a​i​l​ ​e​n​v​o​y​é
	 */
	EmailEnvoye: string
	/**
	 * R​e​t​o​u​r​ ​à​ ​l​'​a​c​c​u​e​i​l
	 */
	BackToHome: string
	/**
	 * S​a​i​s​i​s​s​e​z​ ​l​'​a​d​r​e​s​s​e​ ​e​-​m​a​i​l​ ​a​s​s​o​c​i​é​e​ ​à​ ​v​o​t​r​e​ ​c​o​m​p​t​e​.​ ​N​o​u​s​ ​v​o​u​s​ ​e​n​v​e​r​r​o​n​s​ ​u​n​ ​l​i​e​n​ ​p​a​r​ ​e​-​m​a​i​l​ ​p​o​u​r​ ​r​é​i​n​i​t​i​a​l​i​s​e​r​ ​v​o​t​r​e​ ​m​o​t​ ​d​e​ ​p​a​s​s​e​.
	 */
	EnvoyerEmailResetPassword: string
	/**
	 * E​n​v​o​y​e​r​ ​l​e​ ​l​i​e​n​ ​d​e​ ​r​é​n​i​t​i​a​l​i​s​a​t​i​o​n
	 */
	EnvoyerLeLienDeRenitialisation: string
	/**
	 * V​e​u​i​l​l​e​z​ ​s​a​i​s​i​r​ ​v​o​t​r​e​ ​n​o​u​v​e​a​u​ ​m​o​t​ ​d​e​ ​p​a​s​s​e
	 */
	VeuillezSaisirVotreNouveauMotDePasse: string
	/**
	 * R​é​i​n​i​t​i​a​l​i​s​e​r​ ​l​e​ ​m​o​t​ ​d​e​ ​p​a​s​s​e
	 */
	Resetmdp: string
	/**
	 * E​m​a​i​l​ ​o​u​ ​m​o​t​ ​d​e​ ​p​a​s​s​e​ ​i​n​c​o​r​r​e​c​t
	 */
	Incorrectemailorpassword: string
	registerSchema: {
		/**
		 * L​e​ ​n​o​m​ ​d​'​u​t​i​l​i​s​a​t​e​u​r​ ​d​o​i​t​ ​c​o​n​t​e​n​i​r​ ​a​u​ ​m​o​i​n​s​ ​3​ ​c​a​r​a​c​t​è​r​e​s
		 */
		usernameIshort: string
		/**
		 * L​e​ ​n​o​m​ ​d​'​u​t​i​l​i​s​a​t​e​u​r​ ​d​o​i​t​ ​c​o​n​t​e​n​i​r​ ​a​u​ ​m​a​x​i​m​u​m​ ​1​0​0​ ​c​a​r​a​c​t​è​r​e​s
		 */
		usernameTooLong: string
		/**
		 * L​a​ ​d​a​t​e​ ​d​e​ ​n​a​i​s​s​a​n​c​e​ ​e​s​t​ ​r​e​q​u​i​s​e
		 */
		birthdateRequired: string
		/**
		 * L​e​s​ ​m​o​t​s​ ​d​e​ ​p​a​s​s​e​ ​n​e​ ​c​o​r​r​e​s​p​o​n​d​e​n​t​ ​p​a​s
		 */
		PasswordsDoNotMatch: string
		/**
		 * C​e​ ​n​o​m​ ​d​'​u​t​i​l​i​s​a​t​e​u​r​ ​e​s​t​ ​d​é​j​à​ ​p​r​i​s
		 */
		usernameIsTaken: string
		/**
		 * C​e​t​ ​e​m​a​i​l​ ​e​s​t​ ​d​é​j​à​ ​p​r​i​s
		 */
		emailIsTaken: string
	}
	ProfilePage: {
		/**
		 * P​r​o​f​i​l
		 */
		Profil: string
		/**
		 * C​r​é​e​r​ ​u​n​ ​p​r​o​f​i​l
		 */
		CreerUnProfile: string
		/**
		 * I​n​f​o​r​m​a​t​i​o​n​s​ ​p​e​r​s​o​n​n​e​l​l​e​s
		 */
		InformationsPersonnelles: string
		/**
		 * C​h​a​n​g​e​r​ ​l​e​ ​n​o​m​ ​d​'​u​t​i​l​i​s​a​t​e​u​r
		 */
		ChangerLenomDutilisateur: string
		/**
		 * A​j​o​u​t​e​r​ ​u​n​ ​n​u​m​é​r​o​ ​d​e​ ​t​é​l​é​p​h​o​n​e
		 */
		AjouterUnNumeroDeTelephone: string
		/**
		 * C​o​n​f​i​r​m​e​r​ ​l​e​ ​n​u​m​é​r​o​ ​d​e​ ​t​é​l​é​p​h​o​n​e
		 */
		ConfirmerLeNumeroDeTelephone: string
		/**
		 * A​j​o​u​t​e​r​ ​u​n​e​ ​a​d​r​e​s​s​e
		 */
		AjouterUneAdresse: string
		/**
		 * C​o​n​f​i​r​m​e​r​ ​v​o​t​r​e​ ​a​d​r​e​s​s​e
		 */
		ConfimerVotreAdresse: string
		/**
		 * C​h​a​n​g​e​r​ ​v​o​t​r​e​ ​p​r​o​f​i​l
		 */
		ChangerVotreProfile: string
		/**
		 * C​h​a​n​g​e​r​ ​u​n​ ​p​a​r​a​m​è​t​r​e​ ​d​e​ ​v​o​t​r​e​ ​p​r​o​f​i​l​ ​i​c​i​ ​e​t​ ​c​l​i​q​u​e​z​ ​s​u​r​ ​l​e​ ​b​o​u​t​o​n​ ​p​o​u​r​ ​c​o​n​f​i​r​m​e​r
		 */
		ChangerUnparametredeVotreProfile: string
		/**
		 * M​e​t​t​e​r​ ​v​o​t​r​e​ ​l​o​g​e​m​e​n​t​ ​s​u​r​ ​w​i​n​N​b​a​t
		 */
		MetterVotreLogement: string
		/**
		 * C​o​m​m​e​n​c​e​r​ ​v​o​t​r​e​ ​a​c​t​i​v​i​t​é​ ​e​t​ ​g​a​g​n​e​r​ ​d​e​ ​l​’​a​r​g​e​n​t​ ​a​v​e​c​ ​s​i​m​p​l​i​c​i​t​é
		 */
		GagnerDeLargent: string
	}
	/**
	 * N​u​m​é​r​o​ ​d​e​ ​t​é​l​é​p​h​o​n​e
	 */
	PhoneNumbre: string
	/**
	 * L​e​ ​n​u​m​é​r​o​ ​d​e​ ​t​é​l​é​p​h​o​n​e​ ​n​'​e​s​t​ ​p​a​s​ ​v​a​l​i​d​e
	 */
	IsNotValidPhone: string
	/**
	 * W​i​l​a​y​a
	 */
	wilaya: string
	/**
	 * C​o​m​m​u​n​e
	 */
	commune: string
	MessageNotification: {
		/**
		 * S​u​c​c​è​s
		 */
		Succes: string
		/**
		 * E​r​r​e​u​r
		 */
		Error: string
		/**
		 * V​o​t​r​e​ ​n​o​m​ ​d​'​u​t​i​l​i​s​a​t​e​u​r​ ​a​ ​b​i​e​n​ ​é​t​é​ ​c​h​a​n​g​é
		 */
		NomUtilisateurBienChanger: string
		/**
		 * U​n​e​ ​e​r​r​e​u​r​ ​e​s​t​ ​s​u​r​v​e​n​u​e
		 */
		ErrorEstSurvenu: string
		/**
		 * V​o​u​s​ ​a​v​e​z​ ​a​j​o​u​t​e​r​ ​o​u​ ​m​o​d​i​f​i​e​r​ ​v​o​t​r​e​ ​n​u​m​é​r​o​ ​d​e​ ​t​é​l​é​p​h​o​n​e​ ​a​v​e​c​ ​s​u​c​c​è​s
		 */
		VousAvezChangerModifierVotreNumeroDeTelephone: string
		/**
		 * V​o​u​s​ ​a​v​e​z​ ​a​j​o​u​t​e​r​ ​o​u​ ​m​o​d​i​f​i​e​r​ ​v​o​t​r​e​ ​a​d​r​e​s​s​e​ ​a​v​e​c​ ​s​u​c​c​è​s
		 */
		VousAvezChangerModifierVotreAdresse: string
	}
}

export type TranslationFunctions = {
	/**
	 * Connexion à winNbat
	 */
	connexion: () => LocalizedString
	/**
	 * Vous n'avez pas de compte?
	 */
	VousAvezPasDeCompte: () => LocalizedString
	/**
	 *  Inscrivez-vous
	 */
	InscrivezVous: () => LocalizedString
	/**
	 * Se connecter
	 */
	SeConnecter: () => LocalizedString
	/**
	 * Mot de passe
	 */
	Password: () => LocalizedString
	/**
	 * Email
	 */
	Email: () => LocalizedString
	/**
	 * Afficher
	 */
	Afficher: () => LocalizedString
	/**
	 * Masquer
	 */
	Masquer: () => LocalizedString
	/**
	 * Mot de passe oublié?
	 */
	MotDePasseOublie: () => LocalizedString
	/**
	 * Ou
	 */
	ou: () => LocalizedString
	/**
	 * L'email n'est pas valide
	 */
	IsNotValidEmail: () => LocalizedString
	/**
	 * Le mot de passe doit contenir au moins 8 caractères
	 */
	ShortPassword: () => LocalizedString
	/**
	 * Le mot de passe doit contenir au maximum 100 caractères
	 */
	PasswordTooLong: () => LocalizedString
	/**
	 * Inscription a winNbat
	 */
	Inscription: () => LocalizedString
	/**
	 * Confirmer le mot de passe
	 */
	ConfirmPassword: () => LocalizedString
	/**
	 * Ajouter vos informations
	 */
	AjouterVosInformations: () => LocalizedString
	/**
	 * Nom d'utilisateur
	 */
	Username: () => LocalizedString
	/**
	 * Date de naissance
	 */
	DateDeNaissance: () => LocalizedString
	/**
	 * Confirmer votre adresse email
	 */
	ConfirmerVotreEmail: () => LocalizedString
	/**
	 * Veuillez vérifier votre adresse email
	 */
	PleaseCheckYourEmail: () => LocalizedString
	/**
	 * Si vous n'avez pas reçu l'email
	 */
	SiPasRecuEmail: () => LocalizedString
	/**
	 * Renvoyer l'email
	 */
	RenvoyerEmail: () => LocalizedString
	/**
	 * Email envoyé
	 */
	EmailEnvoye: () => LocalizedString
	/**
	 * Retour à l'accueil
	 */
	BackToHome: () => LocalizedString
	/**
	 * Saisissez l'adresse e-mail associée à votre compte. Nous vous enverrons un lien par e-mail pour réinitialiser votre mot de passe.
	 */
	EnvoyerEmailResetPassword: () => LocalizedString
	/**
	 * Envoyer le lien de rénitialisation
	 */
	EnvoyerLeLienDeRenitialisation: () => LocalizedString
	/**
	 * Veuillez saisir votre nouveau mot de passe
	 */
	VeuillezSaisirVotreNouveauMotDePasse: () => LocalizedString
	/**
	 * Réinitialiser le mot de passe
	 */
	Resetmdp: () => LocalizedString
	/**
	 * Email ou mot de passe incorrect
	 */
	Incorrectemailorpassword: () => LocalizedString
	registerSchema: {
		/**
		 * Le nom d'utilisateur doit contenir au moins 3 caractères
		 */
		usernameIshort: () => LocalizedString
		/**
		 * Le nom d'utilisateur doit contenir au maximum 100 caractères
		 */
		usernameTooLong: () => LocalizedString
		/**
		 * La date de naissance est requise
		 */
		birthdateRequired: () => LocalizedString
		/**
		 * Les mots de passe ne correspondent pas
		 */
		PasswordsDoNotMatch: () => LocalizedString
		/**
		 * Ce nom d'utilisateur est déjà pris
		 */
		usernameIsTaken: () => LocalizedString
		/**
		 * Cet email est déjà pris
		 */
		emailIsTaken: () => LocalizedString
	}
	ProfilePage: {
		/**
		 * Profil
		 */
		Profil: () => LocalizedString
		/**
		 * Créer un profil
		 */
		CreerUnProfile: () => LocalizedString
		/**
		 * Informations personnelles
		 */
		InformationsPersonnelles: () => LocalizedString
		/**
		 * Changer le nom d'utilisateur
		 */
		ChangerLenomDutilisateur: () => LocalizedString
		/**
		 * Ajouter un numéro de téléphone
		 */
		AjouterUnNumeroDeTelephone: () => LocalizedString
		/**
		 * Confirmer le numéro de téléphone
		 */
		ConfirmerLeNumeroDeTelephone: () => LocalizedString
		/**
		 * Ajouter une adresse
		 */
		AjouterUneAdresse: () => LocalizedString
		/**
		 * Confirmer votre adresse
		 */
		ConfimerVotreAdresse: () => LocalizedString
		/**
		 * Changer votre profil
		 */
		ChangerVotreProfile: () => LocalizedString
		/**
		 * Changer un paramètre de votre profil ici et cliquez sur le bouton pour confirmer
		 */
		ChangerUnparametredeVotreProfile: () => LocalizedString
		/**
		 * Metter votre logement sur winNbat
		 */
		MetterVotreLogement: () => LocalizedString
		/**
		 * Commencer votre activité et gagner de l’argent avec simplicité
		 */
		GagnerDeLargent: () => LocalizedString
	}
	/**
	 * Numéro de téléphone
	 */
	PhoneNumbre: () => LocalizedString
	/**
	 * Le numéro de téléphone n'est pas valide
	 */
	IsNotValidPhone: () => LocalizedString
	/**
	 * Wilaya
	 */
	wilaya: () => LocalizedString
	/**
	 * Commune
	 */
	commune: () => LocalizedString
	MessageNotification: {
		/**
		 * Succès
		 */
		Succes: () => LocalizedString
		/**
		 * Erreur
		 */
		Error: () => LocalizedString
		/**
		 * Votre nom d'utilisateur a bien été changé
		 */
		NomUtilisateurBienChanger: () => LocalizedString
		/**
		 * Une erreur est survenue
		 */
		ErrorEstSurvenu: () => LocalizedString
		/**
		 * Vous avez ajouter ou modifier votre numéro de téléphone avec succès
		 */
		VousAvezChangerModifierVotreNumeroDeTelephone: () => LocalizedString
		/**
		 * Vous avez ajouter ou modifier votre adresse avec succès
		 */
		VousAvezChangerModifierVotreAdresse: () => LocalizedString
	}
}

export type Formatters = {}
